
services:
  dev-redis:
    image: redis:7-alpine
    container_name: devhelper_redis
    ports:
      - "6379:6379"
    networks:
      - devnet

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: devhelper_backend
    ports:
      - "8000:8000"
    depends_on:
      - dev-redis
    env_file:
      - ./backend/.env.docker
    networks:
      - devnet

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: devhelper_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://localhost:8000/api
    networks:
      - devnet

networks:
  devnet:
    driver: bridge